# file: .github/workflows/main.yml
name: main
# on – определяет события, которые запускают воркфлоу
on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js '18.x'
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: make install
      - run: make lint
      - run: make test
      - uses: hexlet-components/hello-from-hexlet-action@release
